// Bank data kosakata terstruktur untuk Kuis Hongo Study
window.HONGO_QUIZ_DATA = {
  waktu: {
    title: "Kosa Kata Waktu",
    badge: "時間",
    description:
      "Uji ingatan tentang hari, minggu, bulan, tahun, dan penanggalan khusus.",
    items: [
      { q: "今日", r: "kyou", f: "きょう", a: "Hari ini" },
      { q: "昨日", r: "kinou", f: "きのう", a: "Kemarin" },
      { q: "明日", r: "ashita / asu", f: "あした ・ あす", a: "Besok" },
      { q: "一昨日", r: "ototoi", f: "おととい", a: "2 hari lalu" },
      { q: "明後日", r: "asatte", f: "あさって", a: "2 hari lagi" },
      { q: "毎日", r: "mainichi", f: "まいにち", a: "Setiap hari" },
      { q: "先週", r: "senshuu", f: "せんしゅう", a: "Minggu lalu" },
      { q: "今週", r: "konshuu", f: "こんしゅう", a: "Minggu ini" },
      { q: "来週", r: "raishuu", f: "らいしゅう", a: "Minggu depan" },
      { q: "毎週", r: "maishuu", f: "まいしゅう", a: "Setiap minggu" },
      { q: "先月", r: "sengetsu", f: "せんげつ", a: "Bulan lalu" },
      { q: "今月", r: "kongetsu", f: "こんげつ", a: "Bulan ini" },
      { q: "来月", r: "raigetsu", f: "らいげつ", a: "Bulan depan" },
      { q: "毎月", r: "maitsuki", f: "まいつき", a: "Setiap bulan" },
      { q: "去年", r: "kyonen", f: "きょねん", a: "Tahun lalu" },
      { q: "今年", r: "kotoshi", f: "ことし", a: "Tahun ini" },
      { q: "来年", r: "rainen", f: "らいねん", a: "Tahun depan" },
      { q: "毎年", r: "maitoshi", f: "まいとし", a: "Setiap tahun" },
      { q: "今朝", r: "kesa", f: "けさ", a: "Pagi ini" },
      { q: "今晩", r: "konban", f: "こんばん", a: "Malam ini" },
      { q: "1日", r: "tsuitachi", f: "ついたち", a: "Tanggal 1" },
      { q: "2日", r: "futsuka", f: "ふつか", a: "Tanggal 2" },
      { q: "3日", r: "mikka", f: "みっか", a: "Tanggal 3" },
      { q: "4日", r: "yokka", f: "よっか", a: "Tanggal 4" },
      { q: "5日", r: "itsuka", f: "いつか", a: "Tanggal 5" },
      { q: "7日", r: "nanoka", f: "なのか", a: "Tanggal 7" },
      { q: "8日", r: "youka", f: "ようか", a: "Tanggal 8" },
      { q: "10日", r: "tooka", f: "とうか", a: "Tanggal 10" },
      { q: "14日", r: "juu-yokka", f: "じゅうよっか", a: "Tanggal 14" },
      { q: "20日", r: "hatsuka", f: "はつか", a: "Tanggal 20" },
      { q: "24日", r: "ni-juu-yokka", f: "にじゅうよっか", a: "Tanggal 24" },
      { q: "月曜日", r: "getsu-youbi", f: "げつようび", a: "Senin" },
      { q: "火曜日", r: "ka-youbi", f: "かようび", a: "Selasa" },
      { q: "水曜日", r: "sui-youbi", f: "すいようび", a: "Rabu" },
      { q: "木曜日", r: "moku-youbi", f: "もくようび", a: "Kamis" },
      { q: "金曜日", r: "kin-youbi", f: "きにょうび", a: "Jumat" },
      { q: "土曜日", r: "do-youbi", f: "どようび", a: "Sabtu" },
      { q: "日曜日", r: "nichi-youbi", f: "にちようび", a: "Minggu" },
      { q: "4月", r: "shi-gatsu", f: "しがつ", a: "April" },
      { q: "7月", r: "shichi-gatsu", f: "しちがつ", a: "Juli" },
      { q: "9月", r: "ku-gatsu", f: "くがつ", a: "September" },
    ],
  },

  sekolah: {
    title: "Kosakata Sekolah & Kelas",
    badge: "学校",
    description:
      "Uji kosakata ruangan, fasilitas kelas, alat tulis, dan warga sekolah.",
    items: [
      { q: "学校", r: "gakkoo", f: "がっこう", a: "Sekolah" },
      { q: "小学校", r: "shoogakkoo", f: "しょうがっこう", a: "Sekolah Dasar (SD)" },
      { q: "中学校", r: "chuugakkoo", f: "ちゅうがっこう", a: "SMP" },
      { q: "高校", r: "kookoo", f: "こうこう", a: "SMA" },
      { q: "大学", r: "daigaku", f: "だいがく", a: "Universitas / Perguruan Tinggi" },
      { q: "高校生", r: "kookoosee", f: "こうこうせい", a: "Siswa SMA" },
      { q: "大学生", r: "daigakusee", f: "だいがくせい", a: "Mahasiswa" },
      { q: "先生", r: "sensee", f: "せんせい", a: "Guru / Dosen" },
      { q: "担任", r: "tan'nin", f: "たんにん", a: "Wali Kelas" },
      { q: "校長先生", r: "koochoo sensee", f: "こうちょう せんせい", a: "Kepala Sekolah" },
      { q: "先輩", r: "senpai", f: "せんぱい", a: "Senior" },
      { q: "後輩", r: "koohai", f: "こうはい", a: "Junior" },
      { q: "教室", r: "kyooshitsu", f: "きょうしつ", a: "Ruang Kelas" },
      { q: "図書館", r: "toshokan", f: "としょかん", a: "Perpustakaan" },
      { q: "職員室", r: "shokuin-shitsu", f: "しょくいんしつ", a: "Ruang Guru" },
      { q: "保健室", r: "hoken-shitsu", f: "ほけんしつ", a: "Ruang UKS / Kesehatan" },
      { q: "食堂", r: "shokudoo", f: "しょくどう", a: "Kantin" },
      { q: "体育館", r: "taiikukan", f: "たいいくかん", a: "Gedung Olahraga (GOR)" },
      { q: "机", r: "tsukue", f: "つくえ", a: "Meja" },
      { q: "椅子", r: "isu", f: "いす", a: "Kursi / Bangku" },
      { q: "黒板", r: "kokuban", f: "こくばん", a: "Papan Tulis Hitam" },
      { q: "教科書", r: "kyookasho", f: "きょうかしょ", a: "Buku Pelajaran" },
      { q: "ノート", r: "nooto", f: "のうと", a: "Buku Tulis / Catatan" },
      { q: "えんぴつ", r: "enpitsu", f: "えんぴつ", a: "Pensil" },
      { q: "消しゴム", r: "keshigomu", f: "けしごむ", a: "Penghapus" },
      { q: "定規", r: "joogi", f: "じょうぎ", a: "Penggaris" },
      { q: "はさみ", r: "hasami", f: "はさみ", a: "Gunting" },
      { q: "宿題", r: "shukudai", f: "しゅくだい", a: "Pekerjaan Rumah (PR)" },
      { q: "試験", r: "shiken", f: "しけん", a: "Ujian" },
      { q: "時間割", r: "jikanwari", f: "じかんわり", a: "Jadwal Pelajaran" },
      { q: "部活", r: "bukatsu", f: "ぶかつ", a: "Kegiatan Klub / Ekskul" },
      { q: "夏休み", r: "natsu-yasumi", f: "なつやすみ", a: "Libur Musim Panas" },
    ],
  },

  "mata-pelajaran": {
    title: "Mata Pelajaran & Jurusan",
    badge: "教科",
    description:
      "Uji penguasaan nama mata pelajaran SD, SMP, SMA, dan jurusan perkuliahan.",
    items: [
      { q: "教科", r: "kyooka", f: "きょうか", a: "Mata Pelajaran" },
      { q: "数学", r: "suugaku", f: "すうがく", a: "Matematika (SMP/SMA)" },
      { q: "算数", r: "sansuu", f: "さんすう", a: "Matematika / Berhitung (SD)" },
      { q: "理科", r: "rika", f: "りか", a: "IPA (Sains)" },
      { q: "社会", r: "shakai", f: "しゃかい", a: "IPS (Sosial)" },
      { q: "国語", r: "kokugo", f: "こくご", a: "Bahasa Nasional / Jepang" },
      { q: "英語", r: "eego", f: "えいご", a: "Bahasa Inggris" },
      { q: "物理", r: "butsuri", f: "ぶつり", a: "Fisika" },
      { q: "生物", r: "seebutsu", f: "せいぶつ", a: "Biologi" },
      { q: "化学", r: "kagaku", f: "かがく", a: "Kimia" },
      { q: "歴史", r: "rekishi", f: "れきし", a: "Sejarah" },
      { q: "地理", r: "chiri", f: "ちり", a: "Geografi" },
      { q: "経済", r: "keezai", f: "けいざい", a: "Ekonomi" },
      { q: "保健体育", r: "hoken taiiku", f: "ほけん たいいく", a: "Pendidikan Jasmani (Penjaskes)" },
      { q: "道徳", r: "dootoku", f: "どうとく", a: "Pendidikan Moral / Budi Pekerti" },
      { q: "学部", r: "gakubu", f: "がくぶ", a: "Fakultas" },
      { q: "学科", r: "gakka", f: "がっか", a: "Jurusan / Program Studi" },
      { q: "法学", r: "hoogaku", f: "ほうがく", a: "Ilmu Hukum" },
      { q: "医学", r: "igaku", f: "いがく", a: "Ilmu Kedokteran" },
      { q: "工学", r: "koogaku", f: "こうがく", a: "Teknik (Engineering)" },
      { q: "文学", r: "bungaku", f: "ぶんがく", a: "Sastra" },
      { q: "心理学", r: "shinrigaku", f: "しんりがく", a: "Psikologi" },
      { q: "農学", r: "noogaku", f: "のうがく", a: "Pertanian" },
      { q: "建築学", r: "kenchikugaku", f: "けんちくがく", a: "Arsitektur" },
    ],
  },

  pekerjaan: {
    title: "Pekerjaan & Profesi",
    badge: "仕事",
    description:
      "Uji kosakata berbagai profesi, karier, dan dunia kerja dalam bahasa Jepang.",
    items: [
      { q: "仕事", r: "shigoto", f: "しごと", a: "Pekerjaan" },
      { q: "医者", r: "isha", f: "いしゃ", a: "Dokter" },
      { q: "看護師", r: "kango-shi", f: "かんごし", a: "Perawat" },
      { q: "薬剤師", r: "yakuzai-shi", f: "やくざいし", a: "Apoteker" },
      { q: "教師", r: "kyooshi", f: "きょうし", a: "Guru (Profesi)" },
      { q: "会社員", r: "kaisha-in", f: "かいしゃいん", a: "Karyawan Kantor" },
      { q: "社長", r: "shachoo", f: "しゃちょう", a: "Direktur / Kepala Perusahaan" },
      { q: "エンジニア", r: "enjinia", f: "えんじにあ", a: "Insinyur" },
      { q: "プログラマ", r: "purogurama", f: "ぷろぐらま", a: "Pemrogram (Programmer)" },
      { q: "警察官", r: "keesatsu-kan", f: "けいさつかん", a: "Petugas Polisi" },
      { q: "消防士", r: "shooboo-shi", f: "しょうぼうし", a: "Pemadam Kebakaran" },
      { q: "弁護士", r: "bengo-shi", f: "べんごし", a: "Pengacara" },
      { q: "裁判官", r: "saiban-kan", f: "さいばんかん", a: "Hakim" },
      { q: "記者", r: "kisha", f: "きしゃ", a: "Wartawan / Reporter" },
      { q: "漫画家", r: "manga-ka", f: "まんがか", a: "Komikus (Mangaka)" },
      { q: "声優", r: "seeyuu", f: "せいゆう", a: "Pengisi Suara (Seiyuu)" },
      { q: "料理人", r: "ryoori-nin", f: "りょうりにん", a: "Koki / Juru Masak" },
      { q: "パイロット", r: "pairotto", f: "ぱいろっと", a: "Pilot" },
      { q: "運転手", r: "untenshu", f: "うんてんしゅ", a: "Sopir / Pengemudi" },
      { q: "農家", r: "noo-ka", f: "のうか", a: "Petani" },
      { q: "漁師", r: "ryoo-shi", f: "りょうし", a: "Nelayan" },
      { q: "店員", r: "ten'in", f: "てんいん", a: "Pelayan Toko" },
      { q: "公務員", r: "koomu-in", f: "こうむいん", a: "Pegawai Negeri Sipil (PNS)" },
      { q: "アルバイト", r: "arubaito", f: "あるばいと", a: "Pekerja Paruh Waktu" },
    ],
  },

  orang: {
    title: "Kata Ganti & Kosakata Orang",
    badge: "人",
    description:
      "Uji kosakata kata ganti pronomina, kelompok usia, dan kewarganegaraan.",
    items: [
      { q: "私", r: "watashi", f: "わたし", a: "Saya" },
      { q: "私たち", r: "watashitachi", f: "わたしたち", a: "Kita / Kami" },
      { q: "あなた", r: "anata", f: "あなた", a: "Anda / Kamu" },
      { q: "彼", r: "kare", f: "かれ", a: "Dia (Laki-laki)" },
      { q: "彼女", r: "kanojo", f: "かのじょ", a: "Dia (Perempuan)" },
      { q: "彼ら", r: "karera", f: "かれら", a: "Mereka" },
      { q: "僕", r: "boku", f: "ぼく", a: "Aku (Laki-laki)" },
      { q: "俺", r: "ore", f: "おれ", a: "Gue / Aku (Pria Akrab)" },
      { q: "自分", r: "jibun", f: "じぶん", a: "Diri Sendiri" },
      { q: "みんな", r: "min'na", f: "みんな", a: "Semuanya" },
      { q: "皆さん", r: "minasan", f: "みなさん", a: "Hadirin / Semuanya (Sopan)" },
      { q: "全員", r: "zen'in", f: "ぜんいん", a: "Seluruh Anggota / Semua Orang" },
      { q: "この人", r: "kono hito", f: "この ひと", a: "Orang ini" },
      { q: "あの方", r: "ano kata", f: "あの かた", a: "Orang itu (Hormat)" },
      { q: "人", r: "hito", f: "ひと", a: "Orang" },
      { q: "人々", r: "hitobito", f: "ひとびと", a: "Orang-orang" },
      { q: "人間", r: "ningen", f: "にんげん", a: "Manusia" },
      { q: "男性", r: "dansee", f: "だんせい", a: "Pria / Laki-laki" },
      { q: "女性", r: "josee", f: "じょせい", a: "Wanita / Perempuan" },
      { q: "男の子", r: "otokonoko", f: "おとこのこ", a: "Anak Laki-laki" },
      { q: "女の子", r: "onnanoko", f: "おんなのこ", a: "Anak Perempuan" },
      { q: "友達", r: "tomodachi", f: "ともだち", a: "Teman / Sahabat" },
      { q: "恋人", r: "koibito", f: "こいびと", a: "Pacar / Kekasih" },
      { q: "赤ちゃん", r: "akachan", f: "あかちゃん", a: "Bayi" },
      { q: "子供", r: "kodomo", f: "こども", a: "Anak-anak" },
      { q: "大人", r: "otona", f: "おとな", a: "Orang Dewasa" },
      { q: "若者", r: "wakamono", f: "わかもの", a: "Anak Muda / Pemuda" },
      { q: "お年寄り", r: "otoshiyori", f: "おとしより", a: "Lansia" },
      { q: "外国人", r: "gaikokujin", f: "がいこくじん", a: "Orang Asing" },
      { q: "日本人", r: "nihonjin", f: "にほんじん", a: "Orang Jepang" },
      { q: "インドネシア人", r: "indoneshiajin", f: "いんどねしあじん", a: "Orang Indonesia" },
      { q: "アメリカ人", r: "amerikajin", f: "あめりかじん", a: "Orang Amerika" },
    ],
  },
};
