// Bank data kosakata terstruktur untuk Kuis Hongo Study
window.HONGO_QUIZ_DATA = {
  waktu: {
    title: "Kosa Kata Waktu",
    badge: "時間",
    description:
      "Uji ingatan tentang hari, minggu, bulan, tahun, dan penanggalan khusus.",
    items: [
      { q: "今日", r: "kyou", a: "Hari ini" },
      { q: "昨日", r: "kinou", a: "Kemarin" },
      { q: "明日", r: "ashita / asu", a: "Besok" },
      { q: "一昨日", r: "ototoi", a: "2 hari lalu" },
      { q: "明後日", r: "asatte", a: "2 hari lagi" },
      { q: "毎日", r: "mainichi", a: "Setiap hari" },
      { q: "先週", r: "senshuu", a: "Minggu lalu" },
      { q: "今週", r: "konshuu", a: "Minggu ini" },
      { q: "来週", r: "raishuu", a: "Minggu depan" },
      { q: "毎週", r: "maishuu", a: "Setiap minggu" },
      { q: "先月", r: "sengetsu", a: "Bulan lalu" },
      { q: "今月", r: "kongetsu", a: "Bulan ini" },
      { q: "来月", r: "raigetsu", a: "Bulan depan" },
      { q: "毎月", r: "maitsuki", a: "Setiap bulan" },
      { q: "去年", r: "kyonen", a: "Tahun lalu" },
      { q: "今年", r: "kotoshi", a: "Tahun ini" },
      { q: "来年", r: "rainen", a: "Tahun depan" },
      { q: "毎年", r: "maitoshi", a: "Setiap tahun" },
      { q: "今朝", r: "kesa", a: "Pagi ini" },
      { q: "今晩", r: "konban", a: "Malam ini" },
      { q: "1日", r: "tsuitachi", a: "Tanggal 1" },
      { q: "2日", r: "futsuka", a: "Tanggal 2" },
      { q: "3日", r: "mikka", a: "Tanggal 3" },
      { q: "4日", r: "yokka", a: "Tanggal 4" },
      { q: "5日", r: "itsuka", a: "Tanggal 5" },
      { q: "7日", r: "nanoka", a: "Tanggal 7" },
      { q: "8日", r: "youka", a: "Tanggal 8" },
      { q: "10日", r: "tooka", a: "Tanggal 10" },
      { q: "14日", r: "juu-yokka", a: "Tanggal 14" },
      { q: "20日", r: "hatsuka", a: "Tanggal 20" },
      { q: "24日", r: "ni-juu-yokka", a: "Tanggal 24" },
      { q: "月曜日", r: "getsu-youbi", a: "Senin" },
      { q: "火曜日", r: "ka-youbi", a: "Selasa" },
      { q: "水曜日", r: "sui-youbi", a: "Rabu" },
      { q: "木曜日", r: "moku-youbi", a: "Kamis" },
      { q: "金曜日", r: "kin-youbi", a: "Jumat" },
      { q: "土曜日", r: "do-youbi", a: "Sabtu" },
      { q: "日曜日", r: "nichi-youbi", a: "Minggu" },
      { q: "4月", r: "shi-gatsu", a: "April" },
      { q: "7月", r: "shichi-gatsu", a: "Juli" },
      { q: "9月", r: "ku-gatsu", a: "September" },
    ],
  },

  sekolah: {
    title: "Kosakata Sekolah & Kelas",
    badge: "学校",
    description:
      "Uji kosakata ruangan, fasilitas kelas, alat tulis, dan warga sekolah.",
    items: [
      { q: "学校", r: "gakkoo", a: "Sekolah" },
      { q: "小学校", r: "shoogakkoo", a: "Sekolah Dasar (SD)" },
      { q: "中学校", r: "chuugakkoo", a: "SMP" },
      { q: "高校", r: "kookoo", a: "SMA" },
      { q: "大学", r: "daigaku", a: "Universitas / Perguruan Tinggi" },
      { q: "高校生", r: "kookoosee", a: "Siswa SMA" },
      { q: "大学生", r: "daigakusee", a: "Mahasiswa" },
      { q: "先生", r: "sensee", a: "Guru / Dosen" },
      { q: "担任", r: "tan'nin", a: "Wali Kelas" },
      { q: "校長先生", r: "koochoo sensee", a: "Kepala Sekolah" },
      { q: "先輩", r: "senpai", a: "Senior" },
      { q: "後輩", r: "koohai", a: "Junior" },
      { q: "教室", r: "kyooshitsu", a: "Ruang Kelas" },
      { q: "図書館", r: "toshokan", a: "Perpustakaan" },
      { q: "職員室", r: "shokuin-shitsu", a: "Ruang Guru" },
      { q: "保健室", r: "hoken-shitsu", a: "Ruang UKS / Kesehatan" },
      { q: "食堂", r: "shokudoo", a: "Kantin" },
      { q: "体育館", r: "taiikukan", a: "Gedung Olahraga (GOR)" },
      { q: "机", r: "tsukue", a: "Meja" },
      { q: "椅子", r: "isu", a: "Kursi / Bangku" },
      { q: "黒板", r: "kokuban", a: "Papan Tulis Hitam" },
      { q: "教科書", r: "kyookasho", a: "Buku Pelajaran" },
      { q: "ノート", r: "nooto", a: "Buku Tulis / Catatan" },
      { q: "えんぴつ", r: "enpitsu", a: "Pensil" },
      { q: "消しゴム", r: "keshigomu", a: "Penghapus" },
      { q: "定規", r: "joogi", a: "Penggaris" },
      { q: "はさみ", r: "hasami", a: "Gunting" },
      { q: "宿題", r: "shukudai", a: "Pekerjaan Rumah (PR)" },
      { q: "試験", r: "shiken", a: "Ujian" },
      { q: "時間割", r: "jikanwari", a: "Jadwal Pelajaran" },
      { q: "部活", r: "bukatsu", a: "Kegiatan Klub / Ekskul" },
      { q: "夏休み", r: "natsu-yasumi", a: "Libur Musim Panas" },
    ],
  },

  "mata-pelajaran": {
    title: "Mata Pelajaran & Jurusan",
    badge: "教科",
    description:
      "Uji penguasaan nama mata pelajaran SD, SMP, SMA, dan jurusan perkuliahan.",
    items: [
      { q: "教科", r: "kyooka", a: "Mata Pelajaran" },
      { q: "数学", r: "suugaku", a: "Matematika (SMP/SMA)" },
      { q: "算数", r: "sansuu", a: "Matematika / Berhitung (SD)" },
      { q: "理科", r: "rika", a: "IPA (Sains)" },
      { q: "社会", r: "shakai", a: "IPS (Sosial)" },
      { q: "国語", r: "kokugo", a: "Bahasa Nasional / Jepang" },
      { q: "英語", r: "eego", a: "Bahasa Inggris" },
      { q: "物理", r: "butsuri", a: "Fisika" },
      { q: "生物", r: "seebutsu", a: "Biologi" },
      { q: "化学", r: "kagaku", a: "Kimia" },
      { q: "歴史", r: "rekishi", a: "Sejarah" },
      { q: "地理", r: "chiri", a: "Geografi" },
      { q: "経済", r: "keezai", a: "Ekonomi" },
      { q: "保健体育", r: "hoken taiiku", a: "Pendidikan Jasmani (Penjaskes)" },
      { q: "道徳", r: "dootoku", a: "Pendidikan Moral / Budi Pekerti" },
      { q: "学部", r: "gakubu", a: "Fakultas" },
      { q: "学科", r: "gakka", a: "Jurusan / Program Studi" },
      { q: "法学", r: "hoogaku", a: "Ilmu Hukum" },
      { q: "医学", r: "igaku", a: "Ilmu Kedokteran" },
      { q: "工学", r: "koogaku", a: "Teknik (Engineering)" },
      { q: "文学", r: "bungaku", a: "Sastra" },
      { q: "心理学", r: "shinrigaku", a: "Psikologi" },
      { q: "農学", r: "noogaku", a: "Pertanian" },
      { q: "建築学", r: "kenchikugaku", a: "Arsitektur" },
    ],
  },

  pekerjaan: {
    title: "Pekerjaan & Profesi",
    badge: "仕事",
    description:
      "Uji kosakata berbagai profesi, karier, dan dunia kerja dalam bahasa Jepang.",
    items: [
      { q: "仕事", r: "shigoto", a: "Pekerjaan" },
      { q: "医者", r: "isha", a: "Dokter" },
      { q: "看護師", r: "kango-shi", a: "Perawat" },
      { q: "薬剤師", r: "yakuzai-shi", a: "Apoteker" },
      { q: "教師", r: "kyooshi", a: "Guru (Profesi)" },
      { q: "会社員", r: "kaisha-in", a: "Karyawan Kantor" },
      { q: "社長", r: "shachoo", a: "Direktur / Kepala Perusahaan" },
      { q: "エンジニア", r: "enjinia", a: "Insinyur" },
      { q: "プログラマ", r: "purogurama", a: "Pemrogram (Programmer)" },
      { q: "警察官", r: "keesatsu-kan", a: "Petugas Polisi" },
      { q: "消防士", r: "shooboo-shi", a: "Pemadam Kebakaran" },
      { q: "弁護士", r: "bengo-shi", a: "Pengacara" },
      { q: "裁判官", r: "saiban-kan", a: "Hakim" },
      { q: "記者", r: "kisha", a: "Wartawan / Reporter" },
      { q: "漫画家", r: "manga-ka", a: "Komikus (Mangaka)" },
      { q: "声優", r: "seeyuu", a: "Pengisi Suara (Seiyuu)" },
      { q: "料理人", r: "ryoori-nin", a: "Koki / Juru Masak" },
      { q: "パイロット", r: "pairotto", a: "Pilot" },
      { q: "運転手", r: "untenshu", a: "Sopir / Pengemudi" },
      { q: "農家", r: "noo-ka", a: "Petani" },
      { q: "漁師", r: "ryoo-shi", a: "Nelayan" },
      { q: "店員", r: "ten'in", a: "Pelayan Toko" },
      { q: "公務員", r: "koomu-in", a: "Pegawai Negeri Sipil (PNS)" },
      { q: "アルバイト", r: "arubaito", a: "Pekerja Paruh Waktu" },
    ],
  },

  orang: {
    title: "Kata Ganti & Kosakata Orang",
    badge: "人",
    description:
      "Uji kosakata kata ganti pronomina, kelompok usia, dan kewarganegaraan.",
    items: [
      { q: "私", r: "watashi", a: "Saya" },
      { q: "私たち", r: "watashitachi", a: "Kita / Kami" },
      { q: "あなた", r: "anata", a: "Anda / Kamu" },
      { q: "彼", r: "kare", a: "Dia (Laki-laki)" },
      { q: "彼女", r: "kanojo", a: "Dia (Perempuan)" },
      { q: "彼ら", r: "karera", a: "Mereka" },
      { q: "僕", r: "boku", a: "Aku (Laki-laki)" },
      { q: "俺", r: "ore", a: "Gue / Aku (Pria Akrab)" },
      { q: "自分", r: "jibun", a: "Diri Sendiri" },
      { q: "みんな", r: "min'na", a: "Semuanya" },
      { q: "皆さん", r: "minasan", a: "Hadirin / Semuanya (Sopan)" },
      { q: "全員", r: "zen'in", a: "Seluruh Anggota / Semua Orang" },
      { q: "この人", r: "kono hito", a: "Orang ini" },
      { q: "あの方", r: "ano kata", a: "Orang itu (Hormat)" },
      { q: "人", r: "hito", a: "Orang" },
      { q: "人々", r: "hitobito", a: "Orang-orang" },
      { q: "人間", r: "ningen", a: "Manusia" },
      { q: "男性", r: "dansee", a: "Pria / Laki-laki" },
      { q: "女性", r: "josee", a: "Wanita / Perempuan" },
      { q: "男の子", r: "otokonoko", a: "Anak Laki-laki" },
      { q: "女の子", r: "onnanoko", a: "Anak Perempuan" },
      { q: "友達", r: "tomodachi", a: "Teman / Sahabat" },
      { q: "恋人", r: "koibito", a: "Pacar / Kekasih" },
      { q: "赤ちゃん", r: "akachan", a: "Bayi" },
      { q: "子供", r: "kodomo", a: "Anak-anak" },
      { q: "大人", r: "otona", a: "Orang Dewasa" },
      { q: "若者", r: "wakamono", a: "Anak Muda / Pemuda" },
      { q: "お年寄り", r: "otoshiyori", a: "Lansia" },
      { q: "外国人", r: "gaikokujin", a: "Orang Asing" },
      { q: "日本人", r: "nihonjin", a: "Orang Jepang" },
      { q: "インドネシア人", r: "indoneshiajin", a: "Orang Indonesia" },
      { q: "アメリカ人", r: "amerikajin", a: "Orang Amerika" },
    ],
  },
};
